
CREATE TABLE IF NOT EXISTS job(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job TEXT NOT NULL,
  
)

CREATE TABLE IF NOT EXISTS department(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  department TEXT NOT NULL,
  
)

CREATE TABLE IF NOT EXISTS hired_employees(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  datetime TEXT NOT NULL,
  department_id INTEGER NOT NULL,
  job_id INTEGER NOT NULL
  
)